executable:
  main: Main.hs
  source-dirs: [., lib]
  ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
  dependencies:
    - discord-haskell >= 1.5.2 && < 1.6
    - emoji >= 0.1.0.2 && < 0.2
    - base >= 4.12.0 && < 4.13
    - text >= 1.2.3 && < 1.3
    - transformers >= 0.5.6 && < 0.6
    - deepseq >= 1.4.4 && < 1.5
    - diagrams >= 1.4 && < 1.5
    - diagrams-rasterific >= 1.4.2 && < 1.5
    - diagrams-lib >= 1.4.3 && < 1.5
    - bytestring >= 0.10.8 && < 0.11
    - JuicyPixels >= 3.3.4 && < 3.4
